-- ============================================================
-- Script SQL para crear base de datos en Hostinger phpMyAdmin
-- Sistema de Gestión de Chocolatería
-- Fecha: 21.01.2026
-- ============================================================

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- Desactivar verificación de foreign keys temporalmente
SET FOREIGN_KEY_CHECKS=0;

-- ============================================================
-- Tablas base (sin dependencias)
-- ============================================================

-- Tabla: CATEGORIA
CREATE TABLE IF NOT EXISTS `CATEGORIA` (
  `CAT_CODIGO` varchar(5) NOT NULL,
  `CAT_NOMBRE` varchar(60) NOT NULL,
  `CAT_DESCRIPCION` varchar(60) NOT NULL,
  PRIMARY KEY (`CAT_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: CLIENTES
CREATE TABLE IF NOT EXISTS `CLIENTES` (
  `CLI_ID` int NOT NULL AUTO_INCREMENT,
  `CLI_CEDULA_RUC` varchar(13) NOT NULL,
  `CLI_NOMBRE` varchar(60) NOT NULL,
  `CLI_TELEFONO` varchar(10) NOT NULL,
  `CLI_CORREO` varchar(60) NOT NULL,
  PRIMARY KEY (`CLI_ID`),
  UNIQUE KEY `CLI_CEDULA_RUC` (`CLI_CEDULA_RUC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: PROVEEDORES
CREATE TABLE IF NOT EXISTS `PROVEEDORES` (
  `PRV_ID` int NOT NULL AUTO_INCREMENT,
  `PRV_RUC` varchar(13) NOT NULL,
  `PRV_RAZON_SOCIAL` varchar(60) NOT NULL,
  `PRV_CORREO` varchar(60) NOT NULL,
  `PRV_DIRECCION` varchar(60) NOT NULL,
  `PRV_TELEFONO` varchar(10) NOT NULL,
  PRIMARY KEY (`PRV_ID`),
  UNIQUE KEY `PRV_RUC` (`PRV_RUC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: BODEGAS
CREATE TABLE IF NOT EXISTS `BODEGAS` (
  `BOD_CODIGO` varchar(6) NOT NULL,
  `BOD_DESCRIPCION` varchar(60) NOT NULL,
  `BOD_DIRECCION` varchar(60) NOT NULL,
  `BOD_NOMBRE_ENCARGADO` varchar(60) NOT NULL,
  `BOD_TELEFONO_ENCARGADO` varchar(10) NOT NULL,
  PRIMARY KEY (`BOD_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: TRANSACCION
CREATE TABLE IF NOT EXISTS `TRANSACCION` (
  `TRN_ID` int NOT NULL AUTO_INCREMENT,
  `TRN_POS` int NOT NULL,
  `TRN_NEG` int NOT NULL,
  PRIMARY KEY (`TRN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Tablas con una dependencia
-- ============================================================

-- Tabla: PRODUCTOS (depende de CATEGORIA)
CREATE TABLE IF NOT EXISTS `PRODUCTOS` (
  `PRD_CODIGO` varchar(8) NOT NULL,
  `CAT_CODIGO` varchar(5) NOT NULL,
  `PRD_DESCRIPCION` varchar(60) NOT NULL,
  `PRD_PRECIO` decimal(6,2) NOT NULL,
  `PRD_COSTO_ADQUISICION` decimal(6,2) NOT NULL,
  PRIMARY KEY (`PRD_CODIGO`),
  KEY `FK_PRODUCTO_CAT_PROD_CATEGORI` (`CAT_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: COMPRAS (depende de PROVEEDORES)
CREATE TABLE IF NOT EXISTS `COMPRAS` (
  `CMP_CODIGO` int NOT NULL AUTO_INCREMENT,
  `PRV_ID` int NOT NULL,
  `CMP_FECHA_ENTREGA` date NOT NULL,
  `CMP_ESTADO` varchar(10) NOT NULL,
  PRIMARY KEY (`CMP_CODIGO`),
  KEY `FK_COMPRAS_PRV_COMPR_PROVEEDO` (`PRV_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: FACTURAS (depende de CLIENTES)
CREATE TABLE IF NOT EXISTS `FACTURAS` (
  `FAC_CODIGO` int NOT NULL AUTO_INCREMENT,
  `FAC_FECHA` datetime NOT NULL,
  `FAC_SUBTOTAL` decimal(10,2) NOT NULL,
  `FAC_IVA` decimal(10,2) NOT NULL,
  `FAC_MONTO_TOTAL` decimal(10,2) NOT NULL,
  `FAC_ESTADO` varchar(3) NOT NULL,
  `ID_CARRITO` int NOT NULL,
  `CLI_ID` int NOT NULL,
  PRIMARY KEY (`FAC_CODIGO`),
  KEY `FK_FACTURAS_CLI_FACTU_CLIENTES` (`CLI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: USUARIOS (depende de CLIENTES)
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `USU_ID` int NOT NULL AUTO_INCREMENT,
  `CLI_ID` int NOT NULL,
  `USU_NOMBRE` varchar(60) NOT NULL,
  `USU_CONTRASENA` varchar(60) NOT NULL,
  PRIMARY KEY (`USU_ID`),
  KEY `FK_USUARIOS_USUA_CLIE_CLIENTES` (`CLI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Tablas intermedias y de detalle (múltiples dependencias)
-- ============================================================

-- Tabla: PROXBOD (depende de BODEGAS y PRODUCTOS)
CREATE TABLE IF NOT EXISTS `PROXBOD` (
  `BOD_CODIGO` varchar(6) NOT NULL,
  `PRD_CODIGO` varchar(8) NOT NULL,
  `DET_BOD_CANTIDAD` int NOT NULL,
  `DET_BOD_UBICACION` varchar(60) NOT NULL,
  PRIMARY KEY (`BOD_CODIGO`,`PRD_CODIGO`),
  KEY `FK_PROXBOD_PROD_DET__PRODUCTO` (`PRD_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: PROXCMP (depende de COMPRAS y PRODUCTOS)
CREATE TABLE IF NOT EXISTS `PROXCMP` (
  `CMP_CODIGO` int NOT NULL,
  `PRD_CODIGO` varchar(8) NOT NULL,
  `DET_CMP_CANTIDAD` int NOT NULL,
  `DET_CMP_COSTO_UNITARIO` decimal(10,2) NOT NULL,
  `ESTADO_PROXCMP` varchar(3) NOT NULL,
  PRIMARY KEY (`CMP_CODIGO`,`PRD_CODIGO`),
  KEY `FK_PROXCMP_PRD_DET_C_PRODUCTO` (`PRD_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: PROXFAC (depende de FACTURAS y PRODUCTOS)
CREATE TABLE IF NOT EXISTS `PROXFAC` (
  `FAC_CODIGO` int NOT NULL,
  `PRD_CODIGO` varchar(8) NOT NULL,
  `DET_FAC_CANTIDAD` int NOT NULL,
  `DET_FAC_PRECIO_UNITARIO` decimal(10,2) NOT NULL,
  `ESTADO_PROXFAC` varchar(3) NOT NULL,
  PRIMARY KEY (`FAC_CODIGO`,`PRD_CODIGO`),
  KEY `FK_PROXFAC_PRD_DET_F_PRODUCTO` (`PRD_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: DETALLE_CARRITO (depende de PRODUCTOS)
CREATE TABLE IF NOT EXISTS `DETALLE_CARRITO` (
  `PRD_CODIGO` varchar(8) NOT NULL,
  `CAR_CODIGO` int NOT NULL,
  `DET_CAR_CANTIDAD` int NOT NULL,
  PRIMARY KEY (`PRD_CODIGO`,`CAR_CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: KARDEX (depende de PRODUCTOS, BODEGAS, FACTURAS, COMPRAS, TRANSACCION)
CREATE TABLE IF NOT EXISTS `KARDEX` (
  `KAR_ID` int NOT NULL AUTO_INCREMENT,
  `PRD_CODIGO` varchar(8) NOT NULL,
  `BOD_CODIGO` varchar(6) NOT NULL,
  `FAC_CODIGO` int DEFAULT NULL,
  `CMP_CODIGO` int DEFAULT NULL,
  `TRN_ID` int DEFAULT NULL,
  `KAR_FECHA` datetime NOT NULL,
  `KAR_SALDO` int NOT NULL,
  PRIMARY KEY (`KAR_ID`),
  KEY `FK_KARDEX_PRO_KARD_PRODUCTO` (`PRD_CODIGO`),
  KEY `FK_KARDEX_BOD_KARD_BODEGAS` (`BOD_CODIGO`),
  KEY `FK_KARDEX_FAC_KAR_FACTURAS` (`FAC_CODIGO`),
  KEY `FK_KARDEX_CMP_KAR_COMPRAS` (`CMP_CODIGO`),
  KEY `FK_KARDEX_TRN_KAR_TRANSACC` (`TRN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Agregar Foreign Keys
-- ============================================================

-- PRODUCTOS
ALTER TABLE `PRODUCTOS`
  ADD CONSTRAINT `FK_PRODUCTO_CAT_PROD_CATEGORI` FOREIGN KEY (`CAT_CODIGO`) REFERENCES `CATEGORIA` (`CAT_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- COMPRAS
ALTER TABLE `COMPRAS`
  ADD CONSTRAINT `FK_COMPRAS_PRV_COMPR_PROVEEDO` FOREIGN KEY (`PRV_ID`) REFERENCES `PROVEEDORES` (`PRV_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- FACTURAS
ALTER TABLE `FACTURAS`
  ADD CONSTRAINT `FK_FACTURAS_CLI_FACTU_CLIENTES` FOREIGN KEY (`CLI_ID`) REFERENCES `CLIENTES` (`CLI_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- USUARIOS
ALTER TABLE `USUARIOS`
  ADD CONSTRAINT `FK_USUARIOS_USUA_CLIE_CLIENTES` FOREIGN KEY (`CLI_ID`) REFERENCES `CLIENTES` (`CLI_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- PROXBOD
ALTER TABLE `PROXBOD`
  ADD CONSTRAINT `FK_PROXBOD_BOD_PROXB_BODEGAS` FOREIGN KEY (`BOD_CODIGO`) REFERENCES `BODEGAS` (`BOD_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_PROXBOD_PROD_DET__PRODUCTO` FOREIGN KEY (`PRD_CODIGO`) REFERENCES `PRODUCTOS` (`PRD_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- PROXCMP
ALTER TABLE `PROXCMP`
  ADD CONSTRAINT `FK_PROXCMP_CMP_PROXC_COMPRAS` FOREIGN KEY (`CMP_CODIGO`) REFERENCES `COMPRAS` (`CMP_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_PROXCMP_PRD_DET_C_PRODUCTO` FOREIGN KEY (`PRD_CODIGO`) REFERENCES `PRODUCTOS` (`PRD_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- PROXFAC
ALTER TABLE `PROXFAC`
  ADD CONSTRAINT `FK_PROXFAC_FAC_PROXF_FACTURAS` FOREIGN KEY (`FAC_CODIGO`) REFERENCES `FACTURAS` (`FAC_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_PROXFAC_PRD_DET_F_PRODUCTO` FOREIGN KEY (`PRD_CODIGO`) REFERENCES `PRODUCTOS` (`PRD_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- DETALLE_CARRITO
ALTER TABLE `DETALLE_CARRITO`
  ADD CONSTRAINT `FK_DETALLE__PRD_DET_C_PRODUCTO` FOREIGN KEY (`PRD_CODIGO`) REFERENCES `PRODUCTOS` (`PRD_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- KARDEX
ALTER TABLE `KARDEX`
  ADD CONSTRAINT `FK_KARDEX_PRO_KARD_PRODUCTO` FOREIGN KEY (`PRD_CODIGO`) REFERENCES `PRODUCTOS` (`PRD_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_KARDEX_BOD_KARD_BODEGAS` FOREIGN KEY (`BOD_CODIGO`) REFERENCES `BODEGAS` (`BOD_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_KARDEX_FAC_KAR_FACTURAS` FOREIGN KEY (`FAC_CODIGO`) REFERENCES `FACTURAS` (`FAC_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_KARDEX_CMP_KAR_COMPRAS` FOREIGN KEY (`CMP_CODIGO`) REFERENCES `COMPRAS` (`CMP_CODIGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `FK_KARDEX_TRN_KAR_TRANSACC` FOREIGN KEY (`TRN_ID`) REFERENCES `TRANSACCION` (`TRN_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Reactivar verificación de foreign keys
SET FOREIGN_KEY_CHECKS=1;

-- ============================================================
-- Script completado
-- ============================================================
